// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { MysqlArgs } from "./mysql";
export type Mysql = import("./mysql").Mysql;
export const Mysql: typeof import("./mysql").Mysql = null as any;
utilities.lazyLoad(exports, ["Mysql"], () => require("./mysql"));


// Export enums:
export * from "../types/enums/databases";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "cloud-toolkit-aws:databases:Mysql":
                return new Mysql(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("cloud-toolkit-aws", "databases", _module)
