// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const DeadLetterQueueTypes = {
    PERMISSIVE: "PERMISSIVE",
    RESTRICTIVE: "RESTRICTIVE",
} as const;

/**
 * Dead Letter Queue type that will receive the faulty messages from the base Queue.
 * Permissive - Messages will be sent to the Dead Letter Queue after 10 failed delivery attempts.
 * Restrictive - Messages will be sent to the Dead Letter Queue after the first failed delivery attempt.
 */
export type DeadLetterQueueTypes = (typeof DeadLetterQueueTypes)[keyof typeof DeadLetterQueueTypes];
