"use strict";
// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeadLetterQueueTypes = void 0;
exports.DeadLetterQueueTypes = {
    PERMISSIVE: "PERMISSIVE",
    RESTRICTIVE: "RESTRICTIVE",
};
//# sourceMappingURL=index.js.map