"use strict";
// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.Organization = exports.AccountIam = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
exports.AccountIam = null;
exports.Organization = null;
utilities.lazyLoad(exports, ["AccountIam"], () => require("./accountIam"));
utilities.lazyLoad(exports, ["Organization"], () => require("./organization"));
const _module = {
    version: utilities.getVersion(),
    construct: (name, type, urn) => {
        switch (type) {
            case "cloud-toolkit-aws:landingZone:AccountIam":
                return new exports.AccountIam(name, undefined, { urn });
            case "cloud-toolkit-aws:landingZone:Organization":
                return new exports.Organization(name, undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("cloud-toolkit-aws", "landingZone", _module);
//# sourceMappingURL=index.js.map