"use strict";
// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.types = exports.storage = exports.serverless = exports.landingzone = exports.kubernetes = exports.email = exports.databases = exports.commons = exports.Provider = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
exports.Provider = null;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));
// Export sub-modules:
const commons = require("./commons");
exports.commons = commons;
const databases = require("./databases");
exports.databases = databases;
const email = require("./email");
exports.email = email;
const kubernetes = require("./kubernetes");
exports.kubernetes = kubernetes;
const landingzone = require("./landingzone");
exports.landingzone = landingzone;
const serverless = require("./serverless");
exports.serverless = serverless;
const storage = require("./storage");
exports.storage = storage;
const types = require("./types");
exports.types = types;
pulumi.runtime.registerResourcePackage("cloud-toolkit-aws", {
    version: utilities.getVersion(),
    constructProvider: (name, type, urn) => {
        if (type !== "pulumi:providers:cloud-toolkit-aws") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new exports.Provider(name, undefined, { urn });
    },
});
require("@pulumi/aws");
require("@pulumi/kubernetes");
//# sourceMappingURL=index.js.map