"use strict";
// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotificationTypes = void 0;
exports.NotificationTypes = {
    Bounce: "Bounce",
    Complaint: "Complaint",
    Delivery: "Delivery",
};
//# sourceMappingURL=index.js.map