"use strict";
// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.storage = exports.serverless = exports.kubernetes = exports.email = void 0;
// Export sub-modules:
const email = require("./email");
exports.email = email;
const kubernetes = require("./kubernetes");
exports.kubernetes = kubernetes;
const serverless = require("./serverless");
exports.serverless = serverless;
const storage = require("./storage");
exports.storage = storage;
//# sourceMappingURL=index.js.map