// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

import * as pulumiKubernetes from "@pulumi/kubernetes";
import * as pulumiRandom from "@pulumi/random";

/**
 * ArgoCD is a component that deploy the ArgoCD application in the cluster.
 */
export class ArgoCD extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'cloud-toolkit-aws:kubernetes:ArgoCD';

    /**
     * Returns true if the given object is an instance of ArgoCD.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ArgoCD {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ArgoCD.__pulumiType;
    }

    /**
     * The inital admin password.
     */
    public /*out*/ readonly adminPassword!: pulumi.Output<pulumiRandom.RandomPassword>;
    /**
     * The Helm Chart used to deploy ArgoCD.
     */
    public /*out*/ readonly chart!: pulumi.Output<pulumiKubernetes.helm.v3.Release>;
    /**
     * The Namespace used to deploy the component.
     */
    public /*out*/ readonly namespace!: pulumi.Output<pulumiKubernetes.core.v1.Namespace>;

    /**
     * Create a ArgoCD resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ArgoCDArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["hostname"] = args ? args.hostname : undefined;
            resourceInputs["adminPassword"] = undefined /*out*/;
            resourceInputs["chart"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
        } else {
            resourceInputs["adminPassword"] = undefined /*out*/;
            resourceInputs["chart"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ArgoCD.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ArgoCD resource.
 */
export interface ArgoCDArgs {
    /**
     * The hostname to be used to expose ArgoCD with an Ingress.
     */
    hostname?: pulumi.Input<string>;
}
