// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

import * as pulumiKubernetes from "@pulumi/kubernetes";

export class Calico extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'cloud-toolkit-aws:kubernetes:Calico';

    /**
     * Returns true if the given object is an instance of Calico.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Calico {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Calico.__pulumiType;
    }

    public /*out*/ readonly application!: pulumi.Output<pulumiKubernetes.apiextensions.CustomResource>;
    public /*out*/ readonly installation!: pulumi.Output<pulumiKubernetes.apiextensions.CustomResource>;
    public /*out*/ readonly installationCrd!: pulumi.Output<pulumiKubernetes.yaml.ConfigFile>;
    public /*out*/ readonly namespace!: pulumi.Output<pulumiKubernetes.core.v1.Namespace | undefined>;

    /**
     * Create a Calico resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CalicoArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["application"] = undefined /*out*/;
            resourceInputs["installation"] = undefined /*out*/;
            resourceInputs["installationCrd"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
        } else {
            resourceInputs["application"] = undefined /*out*/;
            resourceInputs["installation"] = undefined /*out*/;
            resourceInputs["installationCrd"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Calico.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Calico resource.
 */
export interface CalicoArgs {
}
