// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

import * as pulumiKubernetes from "@pulumi/kubernetes";

import {Irsa} from "./index";

export class ClusterAutoscaler extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'cloud-toolkit-aws:kubernetes:ClusterAutoscaler';

    /**
     * Returns true if the given object is an instance of ClusterAutoscaler.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClusterAutoscaler {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClusterAutoscaler.__pulumiType;
    }

    public /*out*/ readonly application!: pulumi.Output<pulumiKubernetes.apiextensions.CustomResource>;
    public /*out*/ readonly irsa!: pulumi.Output<Irsa>;
    public /*out*/ readonly namespace!: pulumi.Output<pulumiKubernetes.core.v1.Namespace | undefined>;

    /**
     * Create a ClusterAutoscaler resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClusterAutoscalerArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.clusterName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clusterName'");
            }
            resourceInputs["clusterName"] = args ? args.clusterName : undefined;
            resourceInputs["application"] = undefined /*out*/;
            resourceInputs["irsa"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
        } else {
            resourceInputs["application"] = undefined /*out*/;
            resourceInputs["irsa"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ClusterAutoscaler.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ClusterAutoscaler resource.
 */
export interface ClusterAutoscalerArgs {
    clusterName: pulumi.Input<string>;
}
