// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

import * as pulumiKubernetes from "@pulumi/kubernetes";

/**
 * IngressNginx is a component that deploy the Nginx IngressController to expose applications over HTTP/HTTPS.
 */
export class IngressNginx extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'cloud-toolkit-aws:kubernetes:IngressNginx';

    /**
     * Returns true if the given object is an instance of IngressNginx.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IngressNginx {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IngressNginx.__pulumiType;
    }

    /**
     * The ArgoCD Application to deploy the component.
     */
    public /*out*/ readonly application!: pulumi.Output<pulumiKubernetes.apiextensions.CustomResource>;
    /**
     * The Namespace used to deploy the component.
     */
    public /*out*/ readonly namespace!: pulumi.Output<pulumiKubernetes.core.v1.Namespace | undefined>;

    /**
     * Create a IngressNginx resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IngressNginxArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.className === undefined) && !opts.urn) {
                throw new Error("Missing required property 'className'");
            }
            resourceInputs["className"] = args ? args.className : undefined;
            resourceInputs["public"] = args ? args.public : undefined;
            resourceInputs["whitelist"] = args ? args.whitelist : undefined;
            resourceInputs["application"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
        } else {
            resourceInputs["application"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IngressNginx.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a IngressNginx resource.
 */
export interface IngressNginxArgs {
    /**
     * The Ingress class name.
     */
    className: pulumi.Input<string>;
    /**
     * Expose the IngressController with a public Load Balancer.
     */
    public?: pulumi.Input<boolean>;
    /**
     * The whitelist of CIDR to access to the Ingress Controller.
     */
    whitelist?: pulumi.Input<pulumi.Input<string>[]>;
}
