// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

import * as pulumiAws from "@pulumi/aws";

/**
 * NodeGroup is a component that deploy a Node Group for a Kubernetes cluster.
 */
export class NodeGroup extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'cloud-toolkit-aws:kubernetes:NodeGroup';

    /**
     * Returns true if the given object is an instance of NodeGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NodeGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NodeGroup.__pulumiType;
    }

    /**
     * The EC2 Launch Template used to provision nodes.
     */
    public /*out*/ readonly launchTemplate!: pulumi.Output<pulumiAws.ec2.LaunchTemplate>;
    /**
     * The EKS Node Group.
     */
    public /*out*/ readonly nodeGroup!: pulumi.Output<pulumiAws.eks.NodeGroup>;
    /**
     * The IAM Role assumed by the EKS Nodes.
     */
    public /*out*/ readonly role!: pulumi.Output<pulumiAws.iam.Role>;
    /**
     * The list of IAM Role Policy Attachment used to attach IAM Roles to the EKS Node Group.
     */
    public /*out*/ readonly rolePolicyAttachments!: pulumi.Output<pulumiAws.iam.RolePolicyAttachment[]>;

    /**
     * Create a NodeGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NodeGroupArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.clusterCA === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clusterCA'");
            }
            if ((!args || args.clusterEndpoint === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clusterEndpoint'");
            }
            if ((!args || args.clusterName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clusterName'");
            }
            if ((!args || args.clusterVersion === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clusterVersion'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.subnetIds === undefined) && !opts.urn) {
                throw new Error("Missing required property 'subnetIds'");
            }
            resourceInputs["clusterCA"] = args ? args.clusterCA : undefined;
            resourceInputs["clusterEndpoint"] = args ? args.clusterEndpoint : undefined;
            resourceInputs["clusterName"] = args ? args.clusterName : undefined;
            resourceInputs["clusterVersion"] = args ? args.clusterVersion : undefined;
            resourceInputs["diskSize"] = args ? args.diskSize : undefined;
            resourceInputs["instanceType"] = args ? args.instanceType : undefined;
            resourceInputs["maxCount"] = args ? args.maxCount : undefined;
            resourceInputs["maxUnavailable"] = args ? args.maxUnavailable : undefined;
            resourceInputs["minCount"] = args ? args.minCount : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["subnetIds"] = args ? args.subnetIds : undefined;
            resourceInputs["launchTemplate"] = undefined /*out*/;
            resourceInputs["nodeGroup"] = undefined /*out*/;
            resourceInputs["role"] = undefined /*out*/;
            resourceInputs["rolePolicyAttachments"] = undefined /*out*/;
        } else {
            resourceInputs["launchTemplate"] = undefined /*out*/;
            resourceInputs["nodeGroup"] = undefined /*out*/;
            resourceInputs["role"] = undefined /*out*/;
            resourceInputs["rolePolicyAttachments"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NodeGroup.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a NodeGroup resource.
 */
export interface NodeGroupArgs {
    /**
     * The CA used by the Kubernetes cluster.
     */
    clusterCA: pulumi.Input<string>;
    /**
     * The Kubernetes cluster endpoint.
     */
    clusterEndpoint: pulumi.Input<string>;
    /**
     * The Kubernetes cluster name.
     */
    clusterName: pulumi.Input<string>;
    /**
     * The Kubernetes cluster version.
     */
    clusterVersion: pulumi.Input<string>;
    /**
     * Disk size in GiB for each node. Defaults to 20.
     */
    diskSize?: pulumi.Input<number>;
    /**
     * The aws instance type to use for the nodes. Defaults to "t3.medium".
     */
    instanceType?: pulumi.Input<string>;
    /**
     * The maxium number of nodes running in the node group. Defaults to 2.
     */
    maxCount?: pulumi.Input<number>;
    /**
     * The maximum number of nodes unavailable at once during a version update. Defaults to 1.
     */
    maxUnavailable?: pulumi.Input<number>;
    /**
     * The minimum number of nodes running in the node group. Defaults to 1.
     */
    minCount?: pulumi.Input<number>;
    /**
     * The name that identies the resource.
     */
    name: pulumi.Input<string>;
    /**
     * The list of subnets ids where the nodes will be deployed.
     */
    subnetIds: pulumi.Input<pulumi.Input<string>[]>;
}
