// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package email

// Types of Email Notifications that are covered by Email Sender.
// * Bounce usually occurs when the recipient address does not exist, their inbox is full, the content of the message if flagged or other casuistics.
// * Complaint indicates that the recipient does not want the email that was sent to them. It is usually a proactive action and it is best to remove the recipient address from the mailing list whenever it is.
// * Delivery marks an email as correctly delivered.
type NotificationTypes string

const (
	NotificationTypesBounce    = NotificationTypes("Bounce")
	NotificationTypesComplaint = NotificationTypes("Complaint")
	NotificationTypesDelivery  = NotificationTypes("Delivery")
)

func init() {
}
