"use strict";
// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mysql = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Cloud Toolkit component for Mysql instances.
 */
class Mysql extends pulumi.ComponentResource {
    /**
     * Create a Mysql resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name, args, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.database === undefined) && !opts.urn) {
                throw new Error("Missing required property 'database'");
            }
            if ((!args || args.version === undefined) && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["backup"] = args ? args.backup : undefined;
            resourceInputs["database"] = args ? args.database : undefined;
            resourceInputs["instance"] = args ? args.instance : undefined;
            resourceInputs["networking"] = args ? args.networking : undefined;
            resourceInputs["storage"] = args ? args.storage : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
            resourceInputs["ingressSecurityGroupRules"] = undefined /*out*/;
            resourceInputs["instancePassword"] = undefined /*out*/;
            resourceInputs["secret"] = undefined /*out*/;
            resourceInputs["secretVersion"] = undefined /*out*/;
            resourceInputs["securityGroup"] = undefined /*out*/;
            resourceInputs["subnetGroup"] = undefined /*out*/;
        }
        else {
            resourceInputs["ingressSecurityGroupRules"] = undefined /*out*/;
            resourceInputs["instance"] = undefined /*out*/;
            resourceInputs["instancePassword"] = undefined /*out*/;
            resourceInputs["secret"] = undefined /*out*/;
            resourceInputs["secretVersion"] = undefined /*out*/;
            resourceInputs["securityGroup"] = undefined /*out*/;
            resourceInputs["subnetGroup"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Mysql.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
    /**
     * Returns true if the given object is an instance of Mysql.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Mysql.__pulumiType;
    }
}
exports.Mysql = Mysql;
/** @internal */
Mysql.__pulumiType = 'cloud-toolkit-aws:databases:Mysql';
//# sourceMappingURL=mysql.js.map