# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
import pulumi_aws

__all__ = [
    'AccountMappingArgs',
    'OrganizationalUnitMapping',
]

@pulumi.output_type
class AccountMappingArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "accountName":
            suggest = "account_name"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AccountMappingArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AccountMappingArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AccountMappingArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 account: Optional['pulumi_aws.organizations.Account'] = None,
                 account_name: Optional[str] = None):
        if account is not None:
            pulumi.set(__self__, "account", account)
        if account_name is not None:
            pulumi.set(__self__, "account_name", account_name)

    @property
    @pulumi.getter
    def account(self) -> Optional['pulumi_aws.organizations.Account']:
        return pulumi.get(self, "account")

    @property
    @pulumi.getter(name="accountName")
    def account_name(self) -> Optional[str]:
        return pulumi.get(self, "account_name")


@pulumi.output_type
class OrganizationalUnitMapping(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "accountName":
            suggest = "account_name"
        elif key == "organizationalUnit":
            suggest = "organizational_unit"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in OrganizationalUnitMapping. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        OrganizationalUnitMapping.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        OrganizationalUnitMapping.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 account_name: Optional[str] = None,
                 organizational_unit: Optional['pulumi_aws.organizations.OrganizationalUnit'] = None):
        if account_name is not None:
            pulumi.set(__self__, "account_name", account_name)
        if organizational_unit is not None:
            pulumi.set(__self__, "organizational_unit", organizational_unit)

    @property
    @pulumi.getter(name="accountName")
    def account_name(self) -> Optional[str]:
        return pulumi.get(self, "account_name")

    @property
    @pulumi.getter(name="organizationalUnit")
    def organizational_unit(self) -> Optional['pulumi_aws.organizations.OrganizationalUnit']:
        return pulumi.get(self, "organizational_unit")


