// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const ClusterSubnetsType = {
    Private: "private",
    Public: "public",
} as const;

/**
 * The subnet type
 */
export type ClusterSubnetsType = (typeof ClusterSubnetsType)[keyof typeof ClusterSubnetsType];
