"use strict";
// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.Cluster = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("../utilities");
/**
 * Cluster is a component that deploy a production-ready Kubernetes cluster. It setups the AWS IAM and netwokring, as well many Kubernetes services to run application in production.
 */
class Cluster extends pulumi.ComponentResource {
    /**
     * Create a Cluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name, args, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["api"] = args ? args.api : undefined;
            resourceInputs["nodeGroups"] = args ? args.nodeGroups : undefined;
            resourceInputs["oidcProviders"] = args ? args.oidcProviders : undefined;
            resourceInputs["privateSubnetIds"] = args ? args.privateSubnetIds : undefined;
            resourceInputs["publicSubnetIds"] = args ? args.publicSubnetIds : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
            resourceInputs["vpcId"] = args ? args.vpcId : undefined;
            resourceInputs["cluster"] = undefined /*out*/;
            resourceInputs["cniChart"] = undefined /*out*/;
            resourceInputs["defaultOidcProvider"] = undefined /*out*/;
            resourceInputs["kubeconfig"] = undefined /*out*/;
            resourceInputs["provider"] = undefined /*out*/;
            resourceInputs["provisionerProvider"] = undefined /*out*/;
            resourceInputs["provisionerRole"] = undefined /*out*/;
            resourceInputs["provisionerRolePolicy"] = undefined /*out*/;
            resourceInputs["role"] = undefined /*out*/;
            resourceInputs["rolePolicyAttachment"] = undefined /*out*/;
            resourceInputs["securityGroup"] = undefined /*out*/;
            resourceInputs["subnetTags"] = undefined /*out*/;
        }
        else {
            resourceInputs["cluster"] = undefined /*out*/;
            resourceInputs["cniChart"] = undefined /*out*/;
            resourceInputs["defaultOidcProvider"] = undefined /*out*/;
            resourceInputs["kubeconfig"] = undefined /*out*/;
            resourceInputs["nodeGroups"] = undefined /*out*/;
            resourceInputs["provider"] = undefined /*out*/;
            resourceInputs["provisionerProvider"] = undefined /*out*/;
            resourceInputs["provisionerRole"] = undefined /*out*/;
            resourceInputs["provisionerRolePolicy"] = undefined /*out*/;
            resourceInputs["role"] = undefined /*out*/;
            resourceInputs["rolePolicyAttachment"] = undefined /*out*/;
            resourceInputs["securityGroup"] = undefined /*out*/;
            resourceInputs["subnetTags"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Cluster.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
    /**
     * Returns true if the given object is an instance of Cluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Cluster.__pulumiType;
    }
}
exports.Cluster = Cluster;
/** @internal */
Cluster.__pulumiType = 'cloud-toolkit-aws:kubernetes:Cluster';
//# sourceMappingURL=cluster.js.map