# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'MysqlStorageTypeArgs',
    'MysqlVersion',
]


class MysqlStorageTypeArgs(str, Enum):
    """
    Set of storage type classes for database instance
    """
    STANDARD = "standard"
    IO1 = "io1"
    GP2 = "gp2"


class MysqlVersion(str, Enum):
    """
    Set of allowed versions for the database instance
    """
    V8_0 = "8.0"
    V5_7 = "5.7"
