name: pull-request

on:
  pull_request: {}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: NPM ci
        run: npm ci
        working-directory: provider/cmd/pulumi-resource-cloud-toolkit-aws
      - name: NPM test
        run: npm run test
        working-directory: provider/cmd/pulumi-resource-cloud-toolkit-aws

  build_sdk:
    name: Build SDK
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - run: go version
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Build SDKs
        run: make build_sdk

  build_provider:
    name: Build provider
    runs-on: macos-12
    needs:
      - test
    env:
      bucket: s3://cloud-toolkit-dev
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Create Provider Binaries
        run: make dist
