name: release

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish_binary:
    name: publish
    runs-on: macos-12
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.nodeversion}}
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Create Provider Binaries
        run: make dist
      - name: Create GH Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
    strategy:
      fail-fast: true
      matrix:
        nodeversion:
          - 16.x

  release_nodejs_sdk:
    name: Release NodeJS SDK
    runs-on: macos-12
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Create NodeJS SDK
        run: make build_nodejs_sdk
      - name: Release NodeJS SDK
        run: make release_nodejs_sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release_python_sdk:
    name: Release Python SDK
    runs-on: macos-12
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Create Python SDK
        run: make build_python_sdk
      - name: Release Python SDK
        run: make release_python_sdk
        working-directory: ./sdk/python/bin
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
