// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

import * as pulumiAws from "@pulumi/aws";

/**
 * This is just an example.
 */
export class Example extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'cloud-toolkit-aws:index:Example';

    /**
     * Returns true if the given object is an instance of Example.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Example {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Example.__pulumiType;
    }

    /**
     * The underlying Bucket resource.
     */
    public /*out*/ readonly bucket!: pulumi.Output<pulumiAws.s3.BucketV2>;

    /**
     * Create a Example resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ExampleArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["bucket"] = undefined /*out*/;
        } else {
            resourceInputs["bucket"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Example.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Example resource.
 */
export interface ExampleArgs {
    /**
     * A Swagger specification already in string form to use to initialize the APIGateway.  Note
     * that you must manually provide permission for any route targets to be invoked by API Gateway
     * when using `swaggerString`.
     *
     * Either `swaggerString` or `routes` must be specified.
     */
    name?: pulumi.Input<string>;
}
